# Generated by Django 2.0.5 on 2018-05-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('siteName', models.CharField(max_length=200)),
                ('siteDate', models.DateTimeField(verbose_name='Date of Observation')),
                ('siteObserver', models.CharField(max_length=100)),
                ('nurseryName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nurseryName', models.CharField(max_length=200)),
                ('structureType', models.CharField(max_length=200)),
                ('structureAmount', models.IntegerField(default=0)),
                ('siteName', models.CharField(max_length=200)),
            ],
        ),
    ]
