# Generated by Django 2.0.5 on 2018-06-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dadApp', '0002_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('siteName', models.CharField(max_length=200)),
                ('nurseryName', models.CharField(max_length=200)),
                ('typeOfDamage', models.CharField(max_length=200)),
                ('DamageObservedDate', models.DateTimeField(verbose_name='Date of Observed Damage')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('siteName', models.CharField(max_length=200)),
                ('nurseryName', models.CharField(max_length=200)),
                ('typeOfMaintanence', models.CharField(max_length=200)),
                ('maintenanceDate', models.DateTimeField(verbose_name='Date of Maintenance')),
            ],
        ),
    ]
