# Generated by Django 2.0.5 on 2018-06-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dadApp', '0004_auto_20180601_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='damage',
            name='siteObserver',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='siteObserver',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='species',
            name='siteObserver',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='structure',
            name='siteObserver',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='siteObserver',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
