# Generated by Django 2.0.5 on 2018-06-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dadApp', '0005_auto_20180601_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='percent100Dead',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='species',
            name='percentOfBleached',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='species',
            name='percentOfBroken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='species',
            name='percentOfDiseased',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='species',
            name='speciesLarge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='species',
            name='speciesMedium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='species',
            name='speciesSmall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='species',
            name='speciesXLarge',
            field=models.IntegerField(default=0),
        ),
    ]
