# Generated by Django 2.0.5 on 2018-06-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dadApp', '0007_outplant_outplantspecies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('collectionSite', models.CharField(max_length=200)),
                ('collectionLat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('collectionLong', models.DecimalField(decimal_places=6, max_digits=9)),
                ('collectionObserver', models.CharField(default='Anonymous', max_length=100)),
                ('collectionDate', models.DateTimeField(verbose_name='Date of Collection')),
                ('collectionDepth', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionSpecies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('collectionSite', models.CharField(max_length=200)),
                ('collectionDate', models.DateTimeField(verbose_name='Date of Collection')),
                ('collectionObserver', models.CharField(default='Anonymous', max_length=100)),
                ('collectionSpecies', models.CharField(max_length=200)),
                ('collectionColonySize', models.IntegerField(default=0)),
                ('collectionFragments', models.IntegerField(default=0)),
                ('collectionTLE', models.IntegerField(default=0)),
            ],
        ),
    ]
